version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always    
    environment:       
      MYSQL_DATABASE: 'pay_host'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'payhost_schema_manager'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'r0o7P@ssw0rd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'r0o7P@ssw0rd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - default-db:/var/lib/mysql
# Names our volume
volumes:
  default-db:
